# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension

end

target 'RedwoodApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedwoodApp

  target 'RedwoodAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
